FROM postgres:10-alpine

WORKDIR /usr/src/postgres

ENV POSTGRES_DB=mmorpg
ENV POSTGRES_USER=mmorpg
ENV POSTGRES_PASSWORD=7fc29a74-627c-11e7-b14d-8f0761cdea1e

# COPY mmorpg.sql /docker-entrypoint-initdb.d/
