export MMORPG_REDIS_PASSWORD:=password

.PHONY: all
all : sass
	python3.6 main.py

entr : sass
	ls static/* main.py | entr -r $(MAKE)

.PHONY: i
i : sass
	python3.6 -i main.py

.PHONY: sass
sass : static/css/style.css

%.css : %.scss
	sass $< $@
